services:
  servers_registry:
    image: mallorywittwerepfl/imaging-server-kit:latest
    ports:
      - "8000:8000"
    command: python3 start_registry.py
  rembg:
    build:
      context: ./servers/serverkit-rembg
    depends_on:
      - servers_registry
  skimage-log:
    build:
      context: ./servers/serverkit-skimage-LoG
    depends_on:
      - servers_registry
  stardist:
    build:
      context: ./servers/serverkit-stardist
    depends_on:
      - servers_registry
  cellpose:
    build:
      context: ./servers/serverkit-cellpose
    depends_on:
      - servers_registry
  spotiflow:
    build:
      context: ./servers/serverkit-spotiflow
    depends_on:
      - servers_registry
  orientationpy:
    build:
      context: ./servers/serverkit-orientationpy
    depends_on:
      - servers_registry