services:
  algorithm_hub:
    image: mallorywittwerepfl/imaging-server-kit:latest
    ports:
      - "8000:8000"
    command: python3 start_registry.py
  rembg:
    build:
      context: ./servers/serverkit-rembg
    depends_on:
      - algorithm_hub
  skimage-log:
    build:
      context: ./servers/serverkit-skimage-LoG
    depends_on:
      - algorithm_hub
  stardist:
    build:
      context: ./servers/serverkit-stardist
    depends_on:
      - algorithm_hub
  cellpose:
    build:
      context: ./servers/serverkit-cellpose
    depends_on:
      - algorithm_hub
  spotiflow:
    build:
      context: ./servers/serverkit-spotiflow
    depends_on:
      - algorithm_hub
  orientationpy:
    build:
      context: ./servers/serverkit-orientationpy
    depends_on:
      - algorithm_hub