services:
  servers_registry:
    build:
      context: ./registry
    ports:
      - "8000:8000"

  skimage-log:
    build:
      context: ./servers/serverkit-skimage-LoG
    depends_on:
      - servers_registry

  rembg:
    build:
      context: ./servers/serverkit-rembg
    depends_on:
      - servers_registry
